# -*- coding: utf-8 -*-
"""Mental Health Booster Chatbot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19d4qJINa1MgzK2YQSibJGySUv2n4WOU_
"""

!pip install -q gradio transformers torch openai-whisper

import gradio as gr
import whisper
import torch
from transformers import pipeline

sentiment_analyzer = pipeline(
    "sentiment-analysis",
    model="distilbert-base-uncased-finetuned-sst-2-english"
)

whisper_model = whisper.load_model("base")

def speech_to_text(audio_path):
    result = whisper_model.transcribe(audio_path)
    return result["text"]

def analyze_sentiment(text):
    result = sentiment_analyzer(text)[0]
    return result["label"], result["score"]

def generate_supportive_response(user_text, sentiment):
    if sentiment == "NEGATIVE":
        return (
            "I'm really sorry you're feeling this way. 💙 "
            "It sounds overwhelming, and your feelings are completely valid. "
            "You don’t have to go through this alone. "
            "Would you like to share what has been bothering you the most?"
        )

    elif sentiment == "POSITIVE":
        return (
            "I'm glad to hear some positivity in your words 🌱 "
            "You’re doing something right, even if it doesn’t feel like it. "
            "What’s one small thing that has helped you feel this way?"
        )

    else:
        return (
            "Thank you for sharing how you're feeling. 🤍 "
            "It’s okay to have mixed emotions. "
            "What’s been on your mind lately?"
        )

def mental_health_booster(text_input, audio_input):
    # If audio is provided, convert to text
    if audio_input is not None:
        text_input = speech_to_text(audio_input)

    if not text_input or text_input.strip() == "":
        return "Please type or speak something so I can support you 💬", 0.0

    sentiment, confidence = analyze_sentiment(text_input)

    response = generate_supportive_response(text_input, sentiment)

    return response, round(confidence, 4)

with gr.Blocks(theme="soft", title="🧠 Mental Health Booster Chatbot") as demo:
    gr.Markdown("""
    # 🧠 Empathy AI: Mental Wellness Companion
    ### _Leveraging Generative AI, NLP, Sentiment Analysis, and Speech-to-Text for Empathetic Support._

    This interactive demonstration showcases a robust AI application designed to provide **immediate, empathetic, and supportive responses** based on user input, whether typed or spoken. It's built with a sophisticated pipeline combining:

    -   **Speech-to-Text (Whisper AI)**: Converts spoken words into text, enabling accessibility.
    -   **Natural Language Processing (Hugging Face Transformers)**: Analyzes text for underlying sentiment.
    -   **Generative AI (Custom Logic)**: Crafts contextually appropriate and supportive messages.

    ⚠️ _Disclaimer: This tool is for illustrative purposes only and is not a substitute for professional medical or mental health advice._
    """)

    with gr.Row():
        text_input_comp = gr.Textbox(
            label="💬 Type how you are feeling",
            placeholder="I feel overwhelmed with my workload and just can't seem to cope...",
            lines=5, # Make textbox larger
            scale=1 # Take available width
        )

    with gr.Row():
        audio_input_comp = gr.Audio(
            sources=["microphone"], # Allows microphone input
            type="filepath",
            label="🎤 Or speak here (for accessibility & convenience)",
            scale=1 # Take available width
        )

    with gr.Row():
        submit_button = gr.Button("✨ Get Empathetic Support", variant="primary", scale=1)
        clear_button = gr.Button("🗑️ Clear Inputs", variant="secondary", scale=1)

    with gr.Row():
        output_text_comp = gr.Textbox(
            label="🤍 Empathetic Response",
            interactive=False,
            lines=8, # Make textbox larger for detailed responses
            scale=3 # Take more width
        )
        sentiment_score_comp = gr.Number(
            label="Confidence Score",
            interactive=False,
            precision=4, # Display 4 decimal places
            scale=1 # Take less width
        )

    # Connect the submit button to the function
    submit_button.click(
        fn=mental_health_booster,
        inputs=[text_input_comp, audio_input_comp],
        outputs=[output_text_comp, sentiment_score_comp]
    )

    # Connect the clear button to clear inputs and outputs
    clear_button.click(
        fn=lambda: ["", None, "", 0.0], # Clear text_input, audio_input, output_text, and sentiment_score
        inputs=[],
        outputs=[text_input_comp, audio_input_comp, output_text_comp, sentiment_score_comp]
    )

interface = demo # Assign the Blocks app to the 'interface' variable for launch

interface.launch(share=True)

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# 
# import gradio as gr
# import whisper
# from transformers import pipeline
# 
# # Load models
# sentiment_analyzer = pipeline(
#     "sentiment-analysis",
#     model="distilbert-base-uncased-finetuned-sst-2-english"
# )
# 
# whisper_model = whisper.load_model("base")
# 
# def speech_to_text(audio_path):
#     result = whisper_model.transcribe(audio_path)
#     return result["text"]
# 
# def analyze_sentiment(text):
#     result = sentiment_analyzer(text)[0]
#     return result["label"], result["score"]
# 
# def generate_supportive_response(user_text, sentiment):
#     if sentiment == "NEGATIVE":
#         return (
#             "I'm really sorry you're feeling this way. 💙 "
#             "Your feelings are valid, and you’re not alone. "
#             "Would you like to share what’s been troubling you most?"
#         )
#     elif sentiment == "POSITIVE":
#         return (
#             "It’s nice to hear some positivity 🌱 "
#             "You’re doing better than you think. "
#             "What’s something that helped you feel this way?"
#         )
#     else:
#         return (
#             "Thank you for sharing 🤍 "
#             "It’s okay to feel mixed emotions. "
#             "What’s been on your mind lately?"
#         )
# 
# def mental_health_booster(text_input, audio_input):
#     if audio_input is not None:
#         text_input = speech_to_text(audio_input)
# 
#     if not text_input or text_input.strip() == "":
#         return "Please type or speak something so I can support you 💬", 0.0
# 
#     sentiment, confidence = analyze_sentiment(text_input)
#     response = generate_supportive_response(text_input, sentiment)
# 
#     return response, round(confidence, 4)
# 
# with gr.Blocks(theme="soft", title="🧠 Mental Health Booster Chatbot") as demo:
#     gr.Markdown("# 🧠 Mental Health Booster Chatbot\nAccessible AI support using NLP and Speech-to-Text.")
# 
#     text_input = gr.Textbox(label="💬 Type how you are feeling", lines=4)
#     audio_input = gr.Audio(sources=["microphone"], type="filepath", label="🎤 Or speak here")
#     submit = gr.Button("Get Support")
#     output_text = gr.Textbox(label="🤍 Empathetic Response", lines=6)
#     confidence = gr.Number(label="Confidence Score")
# 
#     submit.click(
#         fn=mental_health_booster,
#         inputs=[text_input, audio_input],
#         outputs=[output_text, confidence]
#     )
# 
# if __name__ == "__main__":
#     demo.launch()
#



